version: "3"

services:
  keycloak:
    container_name: keycloak
    image: ghcr.io/identicum/keycloak:23.0.7
    command: start-dev
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.admin2=disabled
    volumes:
      - ./plugins/keycloak-rest-user/target/keycloak-rest-repo.jar:/opt/keycloak/providers/keycloak-rest-repo.jar
      - ./startup-scripts/:/opt/jboss/startup-scripts/
      - ./custom-scripts/:/opt/jboss/custom-scripts/
      - ./objects/:/opt/jboss/keycloak/objects/
    ports:
      - 8080:8080
  rest-users-api:
    container_name: rest-users-api
    image: ghcr.io/identicum/rest-users-api:latest
    pull_policy: always
    restart: always
    ports:
      - 8081:8081
