name: Build artifact
#  and trigger docker image build

on:
  workflow_call:
    inputs:
      workdir:
        description: Artifact workdir
        required: true
        type: string
    secrets:
      token:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '17'
        cache: 'maven'
    
    - name: Maven - verify
      shell: bash
      run: mvn --batch-mode verify
      working-directory: ${{inputs.workdir}}

    - name: Setup git user
      shell: bash
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

    - name: Prepare release
      shell: bash
      run: mvn -B clean release:prepare release:perform -Ddeveloper.connection=scm:git:https://${{secrets.token}}@github.com/${GITHUB_REPOSITORY}
      working-directory: ${{inputs.workdir}}
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  # docker-build:
  #   needs: build
  #   uses: ./.github/workflows/docker.yml
